@host = https://localhost
@port = 7063


GET https://localhost:7063/api/dishes


PATCH https://localhost:7063/api/dishes/3
Content-Type: application/json

{
  "dishId": 3,
  "updatedDishIngredients": [
    {
      "ingredientId": 2,
      "quantityIngredient": 32,
      "typeOfIngredient": "Feuilles"
    }
  ]
}